"use client";
import { useState, useEffect } from "react";
export default function Page(){
  const [showLogo,setShowLogo]=useState(true);
  const [showFyp,setShowFyp]=useState(false);
  const [showLogin,setShowLogin]=useState(false);
  const [isGuest,setIsGuest]=useState(true);
  const [tab,setTab]=useState("fyp");
  const [theme,setTheme]=useState("dark");
  const [crowns,setCrowns]=useState(842);
  const [wallet,setWallet]=useState(10000000);
  const [creatorBal,setCreatorBal]=useState(0);
  const [appBal,setAppBal]=useState(0);
  const [fypIndex,setFypIndex]=useState(0);
  const [chatMsg,setChatMsg]=useState("");
  const [chats,setChats]=useState([{from:"lagos_queen",txt:"Welcome to V10 Million! 👑"},{from:"heritage_box",txt:"1000 ONLY Lagos - Verified All From Beginning"}]);
  const [user,setUser]=useState(null);
  const [form,setForm]=useState({fullName:"",username:"",email:"",pass:"",agree:false});
  const fyp=[{u:"lagos_queen",c:"1000 ONLY Lagos - Beyond TikTok LEVEL 100",l:"1.2k",cr:842},{u:"heritage_box",c:"Verified All From Beginning - Creator 80%",l:"892",cr:1200},{u:"first_verified",c:"Rose 100 - Crown Him N20 - V10M",l:"2.4k",cr:2100}];
  useEffect(()=>{ const t=setTimeout(()=>{setShowLogo(false); setShowFyp(true);},2200); return()=>clearTimeout(t); },[]);
  const signup=()=>{
    if(!form.fullName||!form.username||!form.email||form.pass.length<6||!form.agree){ alert("Fill Full Name, Username, Email, Pass 6+ and agree 80%"); return; }
    setUser({name:form.fullName,username:form.username}); setIsGuest(false); setShowLogin(false); setShowFyp(false); setWallet(v=>v-20); setCreatorBal(v=>v+16); setAppBal(v=>v+4); setCrowns(v=>v+100);
  };
  const crown=()=>{ if(isGuest){ setShowLogin(true); return; } if(wallet<20){ alert("Fund vault N10M"); return; } setWallet(v=>v-20); setCreatorBal(v=>v+16); setAppBal(v=>v+4); setCrowns(v=>v+1); };
  const sendChat=()=>{ if(!chatMsg.trim()) return; setChats([...chats,{from:user?user.username:"you",txt:chatMsg}]); setChatMsg(""); };
  const TH=theme==="dark"?{bg:"#050507",card:"#101012",text:"#fff",sub:"#888",gold:"#CFA658",border:"#222",nav:"#0A0A0A"}:{bg:"#FFFFFF",card:"#F6F5F2",text:"#000",sub:"#666",gold:"#CFA658",border:"#E8E2D0",nav:"#FFF"};
  return(
    <div style={{background:TH.bg,color:TH.text,minHeight:"100vh",fontFamily:"sans-serif",paddingBottom:72}}>
      <style>{"@keyframes pop{0%{transform:scale(.4) rotate(-5deg);opacity:0}50%{transform:scale(1.18) rotate(2deg);opacity:1}100%{transform:scale(1) rotate(0);opacity:1}} @keyframes fadeOut{to{opacity:0;visibility:hidden}} @keyframes slideUp{from{transform:translateY(100%);opacity:0}to{transform:translateY(0);opacity:1}} @keyframes pulse{0%,100%{box-shadow:0 0 20px #CFA65866}50%{box-shadow:0 0 40px #CFA658AA}}"}</style>
      <div style={{background:"linear-gradient(90deg,#00C853,#CFA658)",color:"#000",padding:"6px",textAlign:"center",fontSize:10,fontWeight:900}}>V10 MILLION ACTIVE - Crowns {crowns} - Rose 100 Creator 80% App 20% - 1000 ONLY Lagos</div>
      {showLogo && <div style={{position:"fixed",inset:0,background:TH.bg,zIndex:9999,display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",animation:"fadeOut.6s ease 1.9s forwards"}}><div style={{width:120,height:120,borderRadius:24,background:TH.gold,display:"flex",alignItems:"center",justifyContent:"center",fontSize:40,fontWeight:900,color:"#000",animation:"pop 1.3s ease forwards"}}>C</div><h1 style={{color:TH.gold,marginTop:16,letterSpacing:3,fontWeight:900,animation:"pop 1.3s ease.15s both"}}>Chat & Chill</h1><p style={{color:TH.sub,fontSize:10,animation:"pop 1.3s ease.3s both"}}>AFRICA CIRCUIT - FRIENDSHIP LOVE BENEFITS - V10M</p></div>}
      {showFyp && <div style={{position:"fixed",inset:0,background:"#000",zIndex:800,display:"flex",justifyContent:"center",animation:"slideUp.4s ease"}}><div style={{width:"100%",maxWidth:420,height:"100vh",background:"#0A0A0A",position:"relative",display:"flex",flexDirection:"column"}}><div style={{position:"absolute",top:10,left:10,right:10,display:"flex",justifyContent:"space-between",zIndex:5}}><span style={{color:"#fff",fontSize:11,background:"#ffffff20",padding:"4px 10px",borderRadius:20}}>FYP LIVE • 842 watching</span><button onClick={()=>setShowFyp(false)} style={{background:"#ffffff20",border:"none",color:"#fff",width:28,height:28,borderRadius:14}}>✕</button></div><div style={{flex:1,display:"flex",alignItems:"center",justifyContent:"center",background:"linear-gradient(180deg,#1A1A1A,#000)"}}><div style={{textAlign:"center"}}><div style={{width:86,height:86,borderRadius:20,background:TH.gold,display:"flex",alignItems:"center",justifyContent:"center",fontSize:32,fontWeight:900,margin:"0 auto 10px",animation:"pulse 2s infinite"}}>C</div><p style={{color:"#fff",fontWeight:800}}>@{fyp[0].u}</p><p style={{color:"#aaa",fontSize:11,marginTop:4}}>{fyp[fypIndex].c}</p></div><div style={{position:"absolute",right:8,bottom:100,display:"flex",flexDirection:"column",gap:10}}><button style={{background:"#ffffff15",border:"none",width:40,height:40,borderRadius:20,color:"#fff"}}>❤️<br/><span style={{fontSize:8}}>{fyp[fypIndex].l}</span></button><button onClick={crown} style={{background:TH.gold,border:"none",width:40,height:40,borderRadius:20,color:"#000",fontWeight:900}}>👑<br/><span style={{fontSize:7}}>{fyp[fypIndex].cr}</span></button></div></div><div style={{background:"#111",padding:10,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",gap:5}}>{fyp.map((_,i)=><div key={i} onClick={()=>setFypIndex(i)} style={{width:14,height:3,background:i===fypIndex?TH.gold:"#333"}}></div>)}</div><button onClick={()=>{setShowFyp(false); setShowLogin(true);}} style={{background:TH.gold,color:"#000",padding:"8px 12px",borderRadius:20,border:"none",fontWeight:900,fontSize:11}}>SIGN UP TO CHAT & STREAM</button></div></div></div>}
      <header style={{display:"flex",justifyContent:"space-between",padding:"12px 14px",borderBottom:"1px solid "+TH.border,alignItems:"center"}}><div style={{display:"flex",gap:8,alignItems:"center"}}><div style={{width:30,height:30,borderRadius:8,background:TH.gold,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:"#000",fontSize:12}}>C</div><span style={{fontSize:13,fontWeight:900}}>Chat & Chill</span><span style={{fontSize:9,background:"#00C853",color:"#fff",padding:"2px 6px",borderRadius:10}}>842 LIVE</span></div><div style={{display:"flex",gap:8,alignItems:"center"}}><span style={{fontSize:9,color:TH.gold,fontWeight:800}}>N{wallet.toLocaleString()}</span><button onClick={()=>setTheme(t=>t==="dark"?"light":"dark")} style={{background:TH.card,border:"1px solid "+TH.border,width:30,height:30,borderRadius:15}}>{theme==="dark"?"☀️":"🌙"}</button><button onClick={()=>isGuest?setShowLogin(true):setIsGuest(true)} style={{background:TH.gold,color:"#000",padding:"5px 10px",borderRadius:16,border:"none",fontWeight:900,fontSize:11}}>{isGuest?"Sign In":user?"@"+user.username:"Out"}</button></div></header>
      {showLogin && <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.9)",zIndex:60,display:"flex",alignItems:"center",justifyContent:"center",padding:18}}><div style={{background:"#fff",color:"#000",padding:20,borderRadius:14,width:"100%",maxWidth:360}}><h3 style={{fontWeight:900}}>Sign Up - Enter V10</h3><p style={{fontSize:11,color:"#666",margin:"6px 0 10px"}}>Creator 80% N16 App 20% N4 Rose 100 - 1000 ONLY Lagos</p><input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Full Name" style={{border:"1px solid #ddd",padding:10,width:"100%",borderRadius:8,marginBottom:7}}/><input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="Username" style={{border:"1px solid #ddd",padding:10,width:"100%",borderRadius:8,marginBottom:7}}/><input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email" style={{border:"1px solid #ddd",padding:10,width:"100%",borderRadius:8,marginBottom:7}}/><input value={form.pass} onChange={e=>setForm({...form,pass:e.target.value})} placeholder="Password 6+ chars" type="password" style={{border:"1px solid #ddd",padding:10,width:"100%",borderRadius:8,marginBottom:10}}/><label style={{display:"flex",gap:6,fontSize:11,marginBottom:12}}><input type="checkbox" checked={form.agree} onChange={e=>setForm({...form,agree:e.target.checked})}/> I agree 80% Creator 20% App Rose 100</label><button onClick={signup} style={{background:"#000",color:"#fff",padding:12,width:"100%",borderRadius:8,border:"none",fontWeight:900}}>Sign Up & +100 Crowns</button><button onClick={()=>setShowLogin(false)} style={{marginTop:8,width:"100%",border:"none",background:"none",color:"#888"}}>Cancel</button></div></div>}
      <main style={{padding:14,maxWidth:480,margin:"0 auto"}}>
        {tab==="fyp" && <div><div style={{background:TH.card,padding:12,borderRadius:12,border:"1px solid "+TH.border}}><p style={{fontSize:13}}>{crowns} Crowns - TikTok shows likes. Instagram shows followers. We show power. Chat + Streaming LIVE.</p><button onClick={crown} style={{marginTop:10,background:TH.gold,color:"#000",padding:13,width:"100%",borderRadius:24,border:"none",fontWeight:900}}>Crown Him N20 - Creator N16 80% App N4 20% Rose 100</button></div><button onClick={()=>setShowFyp(true)} style={{width:"100%",marginTop:10,background:TH.card,border:"1px solid "+TH.border,padding:11,borderRadius:10,fontWeight:800,color:TH.text}}>OPEN FYP LIVE ↗️ Netflix</button></div>}
        {tab==="create" && <div style={{background:TH.card,padding:14,borderRadius:12,border:"1px solid "+TH.border}}><h3 style={{fontWeight:900}}>Go Live - Streaming</h3><div style={{height:110,background:"#111",borderRadius:10,display:"flex",alignItems:"center",justifyContent:"center",marginTop:10,color:"#666"}}>Camera Preview - V10 Live</div><input placeholder="Live Title - e.g. Lagos Night Chat" style={{border:"1px solid "+TH.border,padding:10,width:"100%",borderRadius:8,marginTop:10,background:TH.bg,color:TH.text}}/><div style={{display:"flex",gap:6,marginTop:8}}>{["Friendship","Love","Benefits","Drama","Diaspora"].map(c=><span key={c} style={{fontSize:9,padding:"4px 8px",borderRadius:12,border:"1px solid "+TH.border}}>{c}</span>)}</div><button style={{marginTop:10,background:TH.gold,color:"#000",padding:12,width:"100%",borderRadius:20,border:"none",fontWeight:900}}>Start Streaming - V10</button></div>}
        {tab==="chat" && <div><div style={{background:TH.card,borderRadius:12,border:"1px solid "+TH.border,padding:10}}>{chats.map((m,i)=><div key={i} style={{padding:"8px 0",borderBottom:"1px solid "+TH.border}}><span style={{fontWeight:800,fontSize:12,color:TH.gold}}>@{m.from}: </span><span style={{fontSize:12}}>{m.txt}</span></div>)}</div><div style={{display:"flex",gap:6,marginTop:10}}><input value={chatMsg} onChange={e=>setChatMsg(e.target.value)} placeholder="Chat friendly..." style={{flex:1,border:"1px solid "+TH.border,padding:10,borderRadius:20,background:TH.bg,color:TH.text}}/><button onClick={sendChat} style={{background:TH.gold,color:"#000",padding:"10px 14px",borderRadius:20,border:"none",fontWeight:900}}>Send</button><button onClick={crown} style={{background:TH.text,color:TH.bg,padding:"10px 12px",borderRadius:20,border:"none"}}>👑</button></div></div>}
        {tab==="wallet" && <div><div style={{background:"linear-gradient(135deg,#CFA658,#8C6A2F)",padding:14,borderRadius:12,color:"#000"}}><p style={{fontSize:10,fontWeight:800}}>VAULT V10 MILLION - ACTIVE</p><p style={{fontSize:26,fontWeight:900,marginTop:4}}>N{wallet.toLocaleString()}</p><p style={{fontSize:11,marginTop:6,fontWeight:700}}>Creator N{creatorBal} 80% • App N{appBal} 20% • Rose 100</p></div><div style={{background:TH.card,padding:12,borderRadius:12,marginTop:10,border:"1px solid "+TH.border}}><p style={{fontWeight:800}}>Live Earnings Active</p><p style={{fontSize:11,color:TH.sub,marginTop:4}}>Each Crown = N20 • Creator N16 App N4 • Entertainment Streaming LIVE</p></div></div>}
        {tab==="profile" && <div style={{background:TH.card,padding:14,borderRadius:12,border:"1px solid "+TH.border,textAlign:"center"}}>{isGuest?<div><div style={{width:60,height:60,borderRadius:30,background:TH.gold,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:"#000",margin:"0 auto"}}>C</div><p style={{fontWeight:900,marginTop:8}}>Guest - Join 1000 ONLY Lagos</p><button onClick={()=>setShowLogin(true)} style={{marginTop:10,background:TH.gold,color:"#000",padding:10,width:"100%",borderRadius:20,border:"none",fontWeight:900}}>Sign Up - V10 Active</button></div>:<div><div style={{width:60,height:60,borderRadius:30,background:TH.gold,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:"#000",margin:"0 auto"}}>{user.username[0].toUpperCase()}</div><p style={{fontWeight:900,marginTop:6}}>@{user.username}</p><p style={{fontSize:11,color:TH.sub}}>{user.name} • {crowns} Crowns • Level 58 • Verified</p><p style={{fontSize:10,marginTop:6,color:TH.gold,fontWeight:800}}>1000 ONLY Lagos - Creator 80% App 20% - V10M ACTIVE</p></div>}</div>}
      </main>
      <nav style={{position:"fixed",bottom:0,left:0,right:0,height:68,background:TH.nav,borderTop:"1px solid "+TH.border,display:"flex",justifyContent:"space-around",alignItems:"center",zIndex:40}}>
        {[{k:"fyp",l:"FYP",i:"◎"},{k:"create",l:"LIVE",i:"+"},{k:"chat",l:"CHAT",i:"💬"},{k:"wallet",l:"WALLET",i:"₦"},{k:"profile",l:"PROFILE",i:"◐"}].map(t=>{ const a=tab===t.k; return(<button key={t.k} onClick={()=>{ setTab(t.k); if(t.k==="fyp") setShowFyp(true); }} style={{background:"none",border:"none",display:"flex",flexDirection:"column",alignItems:"center",color:a?TH.gold:TH.sub}}><div style={{width:t.k==="create"?42:26,height:t.k==="create"?42:26,borderRadius:t.k==="create"?21:13,background:t.k==="create"?TH.gold:"transparent",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:t.k==="create"?"#000":a?TH.gold:TH.sub,border:"1px solid "+(a?TH.gold:TH.border)}}>{t.i}</div><span style={{fontSize:9,fontWeight:a?800:500,marginTop:2}}>{t.l}</span></button>); })}
      </nav>
    </div>
  );
}
